### ISSUE TITLE
Use/ignore specific arguments when memoizing

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaCollections/Memoize.jl#23]
Is there a way to memoize ignoring one argument?
e.g.
```julia
function foo!(v, x)
  v[1] = norm(x)
  v[2] = sum(x)
  return v
end
```
Can I ignore the value of v? Thanks in advance.

**Comment by cstjean** [comment]
@kmsquire I don't know what you think, but to me this looks like a misuse of memoization. You can achieve the same thing more clearly with

```julia
@memoize x_properties(x) = (norm(x), sum(x))
function foo!(v, x)
   v[1], v[2] = x_properties(x)
   return v
end
```

I'll close, but I'm open to arguments...
