### ISSUE TITLE
Feature request: cache invalidation

### ISSUE THREAD

**Issue by tk3369** [JuliaCollections/Memoize.jl#37]
It seems that the cache will keep growing and never freed.

Couple of ideas:
1. Allow user to invalidate the entire cache and free the memory when it's no longer needed.
2. Allow user to specify a max amount of memory for cache. Exceeding max memory size would kick out the oldest entry (like LRU cache).
3. Allow user to specify the last N call results.  Oldest one is kicked out.

**Comment by PharmCat** [comment]
In simulation tasks leads to memory leak/

**Comment by Wikunia** [comment]
Would also be nice to have a way for being able to benchmark a memoized function i.e. having a fibonacci function and want to benchmark it on `fib(100)` is useless as it's memoized after the first run.

**Comment by cstjean** [comment]
> Allow user to specify the last N call results. Oldest one is kicked out.

You can already use a LRUCache for that.

**Comment by cstjean** [comment]
I'll say that `LRUCache` is a nice, modular solution...
