### ISSUE TITLE
Conditional memoization for caching functions with heavy IO

### ISSUE THREAD

**Issue by sebastianpech** [JuliaCollections/Memoize.jl#56]
I was thinking of using `Memoize.jl` for improving some functions that do heavy IO. The thing is, that I would like to not use the cached version, if an involved file changed. Is it somehow possible to achieve this with `Memoize.jl`, so like having a condition attached to the memoized function that checks if the file was changed since the last function call?

**Comment by sebastianpech** [comment]
Just figured out a pretty simple solution. I just pass `mtime(file)` as an extra argument to the function with `@memoize`.

**Comment by cstjean** [comment]
Yeah, that's what I do too, I think it's the standard solution. `@memoize(..., _hidden_memo_arg=mtime(file))`
