### ISSUE TITLE
Invalidate cache for Mutable struct

### ISSUE THREAD

**Issue by Moelf** [JuliaCollections/Memoize.jl#75]
```
julia> using Memoize

julia> mutable struct Square
           side
       end

julia> @memoize area(s::Square) = s.side^2

julia> a = Square(3)
Square(3)

julia> area(a)
9

julia> a.side = 2
2

julia> area(a)
9
```

Inspired by https://pypi.org/project/cached-property/ to check if this would work.

I think the problem is:
- need to compute hash based on properties of a mutable struct
- invalidate cache based on not ID but the hash for mutable struct
- might want an additional/different keyword to help to hint if we want to memorize based on mutable struct hash

**Comment by Moelf** [comment]
```
julia> mutable struct Square
           side
       end

julia> Base.hash(s::Square, h::UInt64) = hash(s.side, h)

julia> using Memoize

julia> @memoize Dict area(s::Square) = (sleep(2); s.side^2)
area (generic function with 1 method)

julia> a = Square(3)
Square(3)

julia> @time area(a)
  2.006560 seconds (750 allocations: 52.971 KiB, 0.17% compilation time)
9

julia> a.side = 2
2

julia> @time area(a)
  2.003059 seconds (7 allocations: 176 bytes)
4

julia> @time area(a)
  0.000003 seconds (2 allocations: 32 bytes)
4
```

using `Dict` with a costume hashing works

**Comment by cstjean** [comment]
Yeah, as you found out, custom hashes can work. I don't think there's a perfect answer out there, at least not in Julia. You just need to make sure that your hash is consistent with whatever memoization you're performing.

FWIW, I don't really see a situation where I would memoize a function of a mutable struct. Instead, I would do something like 

```julia
@memoize Dict area(l::Float64) = (sleep(2); s.side^2)
area(s::Square) = area(s.side)
```

then the problem naturally disappears.

I'll close this, but I'm still open to discussion...
